# Generated by Django 4.2.30 on 2026-06-12 06:10

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=files.models.file_upload_path)),
                ('file_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('file_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('ref_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='files.storedfile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
