# Generated by Django 4.2.30 on 2026-06-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_is_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['original_filename'], name='files_file_origina_63129f_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_at'], name='files_file_uploade_726d10_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_deleted'], name='files_file_is_dele_6ea6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['file_type'], name='files_store_file_ty_0233f9_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['size'], name='files_store_size_e0ef4f_idx'),
        ),
    ]
